import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { icons } from "lucide";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function pascalCase(value) {
  return value.split("-").map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join("");
}

async function usedIconNames() {
  const source = `${await readFile(path.join(root, "web", "index.html"), "utf8")}\n${await readFile(path.join(root, "web", "app.js"), "utf8")}`;
  const candidates = [...source.matchAll(/["'`]([a-z][a-z0-9-]{1,50})["'`]/g)].map((match) => match[1]);
  return [...new Set(candidates.filter((name) => Array.isArray(icons[pascalCase(name)])))].sort();
}

export async function buildLucideSubset() {
  const names = await usedIconNames();
  const nodes = Object.fromEntries(names.map((name) => [name, icons[pascalCase(name)]]));
  const source = `/* Generated by scripts/build-icons.mjs. */\n(function (global) {\n  "use strict";\n  const icons = ${JSON.stringify(nodes)};\n  const defaults = { xmlns: "http://www.w3.org/2000/svg", width: "24", height: "24", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round", "aria-hidden": "true" };\n\n  function createIcons(options = {}) {\n    const root = options.root || document;\n    const custom = options.attrs || {};\n    for (const element of root.querySelectorAll("[data-lucide]")) {\n      const name = element.getAttribute("data-lucide");\n      const nodes = icons[name];\n      if (!nodes) {\n        console.warn(\`Unknown Lucide icon: \${name}\`);\n        continue;\n      }\n      const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");\n      const original = Object.fromEntries([...element.attributes].map((attribute) => [attribute.name, attribute.value]));\n      delete original["data-lucide"];\n      const className = ["lucide", \`lucide-\${name}\`, original.class].filter(Boolean).join(" ");\n      delete original.class;\n      for (const [key, value] of Object.entries({ ...defaults, ...custom, ...original, class: className })) {\n        svg.setAttribute(key, String(value));\n      }\n      for (const [tag, attributes] of nodes) {\n        const child = document.createElementNS("http://www.w3.org/2000/svg", tag);\n        for (const [key, value] of Object.entries(attributes)) child.setAttribute(key, String(value));\n        svg.append(child);\n      }\n      element.replaceWith(svg);\n    }\n  }\n\n  global.lucide = { createIcons };\n})(window);\n`;
  return { icons: names, source };
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const result = await buildLucideSubset();
  await writeFile(path.join(root, "web", "lucide.js"), result.source, "utf8");
  console.log(`Generated ${result.icons.length} Lucide icons`);
}
